<div class="container">
   <div class="row">
      <h2 class="h2 col-xs-12"><?php $this->getPageTitle(); ?></h2>
   </div>
   <div class="row">
       <?php $this->renderView('alerts/_success'); ?>
       <?php $this->renderView('alerts/_error'); ?>
   </div>
   <div class="row">
   <div class="cols-xs-12 col-xs-offset-0 cold-md-8 col-md-offset-2">
       <h2 class="h2 text-center">Micro Framework PHP</h2>
       <p>Este é um micro framework MVC em PHP, construído como exercício do conteúdo didático do
           curso "Micro Framework do Zero" disponibilizado no canal TJG Web no YouTube.
       </p>
       <p>
           O Intuito deste curso é esclarecer os conceitos e o funcionamento dos grandes frameworks de renome
           já consagrados hoje no mercado.
           Depois deste curso o aluno entenderá melhor os cursos oferecidos na Internet de frameworks como Laravel, Zend, CakePHP, etc
       </p>
   </div>
   </div>
</div>
