<div class="container">
   <h3 class="h3"><?php echo $this->getPageTitle(); ?></h3>
    <?php $this->renderView('alerts/_error'); ?>
   
   <form action="/posts/<?php echo $this->view->post->id; ?>/update" method="post" accept-charset="utf-8">
      <div class="form-group">
         <label for="title">Title</label>
         <input type="text" name="title" class="form-control" value="<?php echo $this->view->post->title; ?>">
      </div>
      <div class="form-group">
         <label for="content">Content</label>
         <textarea name="content" class="form-control" rows="15"><?php echo $this->view->post->content; ?></textarea>
      </div>
      <a href="/posts" class="btn btn-default">Cancel</a>
      <button type="submit" class="btn btn-primary">Save</button>
   </form>
</div>