<div class="container">
   <div class="row">
      <h1 class="h1">
         <?php echo  $this->getPageTitle(); ?>
         <a href="/posts/create" class="btn btn-default pull-right">
            <i class="glyphicon glyphicon-plus"></i>
            New Post</a>
      </h1>
   </div>
   <?php foreach ($this->view->posts as $post): ?>
   <div class="row">
      <h3 class="h3">
         <a href="<?php echo "/posts/" . $post->id . "/show"; ?>">
         <?php echo $post->title; ?>
         </a>
      </h3>
      <p class="text-justify"><?php echo $post->content; ?></p>
       <p class="text-right">
           <a href="/posts/<?php echo $post->id; ?>/edit" class="btn btn-warning btn-xs">
               <i class="glyphicon glyphicon-pencil"></i>
           </a>
       </p>
      <hr>
   </div>
   <?php endforeach; ?>
</div>